spring.application.name=PatientExerciseManager
spring.datasource.username=clinic_user
spring.datasource.password=MyPassword123
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_app
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver




