spring.application.name=PatientExerciseManager
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_app
spring.datasource.username=client_user
spring.datasource.password=MyPassword123!
spring.datasource.driver-class-name=org.postgresql.Driver




